### ISSUE TITLE
URLS How to fix

### ISSUE THREAD

**Issue by InfoDevkota** [Classof2020/WT-Notes#1]
Your site is published at http://ww1.classof2020.xyz/WT-Notes/ But there is 404 not found. @MegaMind98

**Comment by MegaMind98** [comment]
Lol. I can't fix that. Give me few hours to fix that.

**Comment by MegaMind98** [comment]
That was weird. The problem was due you named the default webpage as 'Index.html'. Renamed it to 'index.html' and voilà, we're done now. Thank you, @InfoDevkota!

**Comment by MegaMind98** [comment]
Should I close this?

**Comment by InfoDevkota** [comment]
Done ! Thanks :)
